In [ ]:
import numpy as np
import pandas as pd
import spacy
import json
from sklearn.metrics import f1_score, confusion_matrix, roc_curve

In [0]:
nlp = spacy.load('en_core_web_sm')
f = open('OntoNotes.json', "r")
train_data = json.loads(f.read())

In [0]:
ls = []
for i in range(len(train_data)):
    ls.append(train_data[i][0])

In [0]:
true = []
for _, annotations in train_data:
    for ent in annotations.get('entities'):
        if ent[2] == 'ORG':
            true.append(1)
            break
        else:
            true.append(0)
            break

In [0]:
pred = []
nt_annt = []
for sentence in ls:
    doc = nlp(sentence)
    if not doc.ents:
        pred.append(-1)
        nt_annt.append(sentence)
    for ent in doc.ents:
        if ent.label_ == 'ORG':
            pred.append(1)
            break
        else:
            pred.append(0)
            break

In [6]:
f1_score(true,pred,average=None)

array([0.        , 0.98101418, 0.91691935])

In [7]:
confusion_matrix(true, pred)

array([[   0,    0,    0],
       [  25, 4082,   98],
       [   4,   35,  756]])

In [0]:
fpr, tpr, thresholds = roc_curve(true, pred, pos_label=None)

In [9]:
fpr, tpr, thresholds

(array([0.        , 0.02330559, 0.9940547 , 1.        ]),
 array([0.        , 0.9509434 , 0.99496855, 1.        ]),
 array([ 2,  1,  0, -1]))

In [12]:

dct = {}
for text, annotations in train_data:
    temp = []
    if text in nt_annt:
        for ent in annotations.get('entities'):
            temp.append(ent[2])
        dct[text] = temp

dct     

{"A breakthrough in the investigation of the terrorist attack on the `` USS Cole . ''": ['PRODUCT'],
 'A senior enlisted man says he would have been killed if he had not been called to a meeting moments before the blast .': ['TIME'],
 'Actor Drugewbo Unitich tells how the show began .': ['PERSON'],
 'Considering the prices , uh , people feel that a discount of over 20,000 Yuan in this period is quite appropriate .': ['QUANTITY'],
 'He no longer expects to see the end of the cave in his lifetime .': ['DATE'],
 "If this is one way that we can send the signal that terrorists need to be held accountable for what they do , that 's what this is about .": ['CARDINAL'],
 'In fact , equal protection became the single issue this divided court could find a majority to support .': ['CARDINAL'],
 "It 's the latest hit by the satirical theater called `` Index '' .": ['ORG'],
 'It is one of the major questions that was supposed to be addressed after the stoning and shooting had stopped .': ['CARDINAL

In [0]:
f_ = open('Enron_sentences.json', "r")

target_data = json.loads(f_.read())

In [0]:
lst_txt=[]
for i in range(len(target_data)):
    lst_txt.append(target_data[i].get('text'))

In [0]:
lst_he = []
for i in range(len(target_data)):
    vals = list((target_data[i].get('human_entities').values()))
    if vals:
        lst_he.append(vals[0])
    else:
        lst_he.append('No_changes')

In [0]:
lst_me = []
for i in range(len(target_data)):
    temp = []
    if target_data[i].get('machine_entities'):
        for ents in target_data[i].get('machine_entities'):
            temp.append(ents[2])
        lst_me.append(temp)
    else:
        lst_me.append([])

In [0]:
df = pd.DataFrame()

In [0]:
dict_clmns = {
    'Text': lst_txt,
    'machine_entities': lst_me,
    'human_entities': lst_he
}
df = df.assign(**dict_clmns)

In [22]:
df

Text  ...                         human_entities
0    Shelley: Do you have any information on Projec...  ...                             No_changes
1    The address list on the memo below contains th...  ...                             No_changes
2    Mary, Jason Orta from the CEC called me to inf...  ...                             No_changes
3    Sierra Pacific was listed as CEC 10016 and sho...  ...                             No_changes
4    I have made this correction in EPMI's CEC fili...  ...               [[31, 35, ORG, machine]]
..                                                 ...  ...                                    ...
305  I added Meredith's photo to the web page below...  ...                             No_changes
306  I got him a subscription to Sports Illustrated...  ...                             No_changes
307  I assume that all ENA Upstream deal makers goi...  ...                    [[18, 21, , human]]
308  The ERCOT Board accepted the 3 CSC 4 CM Zone m...  ...  [[0, 3, , human], [4, 9, ORG, human]]
309  Paul I am still looking for information relati...  ...                 [[64, 66, ORG, human]]

[310 rows x 3 columns]